### ISSUE TITLE
make will not run

### ISSUE THREAD

**Issue by tuvok81** [ON5HB/rsp_tcp#1]
i have download with git clone the files..
i have run with **sh SDRplay_RSP_API-Linux-2.13.1.run**
this install the usb lib

Press y and RETURN to accept the license agreement and continue with
the installation, or press n and RETURN to exit the installer [y/n] y
Architecture: x86_64
API Version: 2.13
Remove old libraries...
Install /usr/local/lib/libmirsdrapi-rsp.so.2.13
Remove old header files...
Install /usr/local/include/mirsdrapi-rsp.h
Udev rules directory found, adding rules...
Libusb found, continuing...
Finished.

than i have problems to compile the rsp_tcp with your manual

root@wmk:/home/websdr/SDRPlay_RSP1A/rsp_tcp# mkdir build
root@wmk:/home/websdr/SDRPlay_RSP1A/rsp_tcp# cd build/
root@wmk:/home/websdr/SDRPlay_RSP1A/rsp_tcp/build# cmake ..
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is unknown
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.

-- Configuring incomplete, errors occurred!
See also "/home/websdr/SDRPlay_RSP1A/rsp_tcp/build/CMakeFiles/CMakeOutput.log".
See also "/home/websdr/SDRPlay_RSP1A/rsp_tcp/build/CMakeFiles/CMakeError.log".
root@wmk:/home/websdr/SDRPlay_RSP1A/rsp_tcp/build# make
make: *** No targets specified and no makefile found.  Stop.

i have test a other step but nothing
root@wmk:/home/websdr/SDRPlay_RSP1A/rsp_tcp/build# cd ..
root@wmk:/home/websdr/SDRPlay_RSP1A/rsp_tcp# make
make: *** No targets specified and no makefile found.  Stop.

i hope i have make the correct things

**Comment by tuvok81** [comment]
need package apt install build-essential

**Comment by ON5HB** [comment]
Added in the readme.
