### ISSUE TITLE
openwrt

### ISSUE THREAD

**Issue by pyopower** [ON5HB/rsp_tcp#2]
Congratulations on the magnificent work.Is it possible to compile and install on openwrt routers as rtl_tcp?. I have a small mt-300 that works wonderfully with rtl_tcp and it would be great to have rsp_tcp as well.Greetings

**Comment by ON5HB** [comment]
I compiled the driver on RaspberryPi4 and Linux 64bit, however, I do believe a router isn't powerful enough to handle the load of the receiver.
