### ISSUE TITLE
Question: SDRPlay new API 3.12

### ISSUE THREAD

**Issue by tuvok81** [ON5HB/rsp_tcp#3]
Hello,
will the rsp_tcp also run in the future for the SDRPlay API 3.12? 
[https://www.sdrplay.com/api/](url)

Thank you for your nice work

**Comment by ON5HB** [comment]
No idea, I do not use this api.

Sorry.

Bas ON5HB.

tuvok81 ***@***.***> schreef op 16 december 2023 13:14:11 CET:
